version: build.{build}
image: Visual Studio 2019
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\Packaging\package-Syncopq.ps1 $nuget_version
test_script:
- cmd: >-
    nunit3-console Syncopq.Testing.Core\bin\debug\Syncopq.Testing.Core.dll --result=myresults.xml;format=AppVeyor
    
artifacts:
- path: Syncopq.Core\bin\Debug
  name: Dll
- path: Packaging\.nupkg\Syncopq.*.nupkg
  name: Nuget packages
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    branch: develop
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    APPVEYOR_REPO_TAG: true