pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- script: 'gitversion /l console /output buildserver /updateAssemblyInfo'
  displayName: 'Run GitVersion'
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: '5.4.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '**\*.sln'

- task: VSBuild@1
  displayName: 'Build solution *.sln'
  inputs:
    solution: 'Syncopq.sln'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: 'Syncopq.Testing\bin\debug\Syncopq.Testing.dll'
    vsTestVersion: "Latest"
    codeCoverageEnabled: false
    diagnosticsEnabled: True

- task: PowerShell@2
  displayName: 'Package Nuget'
  inputs:
    targetType: filePath
    filePath: './.packages\package-Syncopq.ps1'
    arguments: '$env:GitVersion_NuGetVersion'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\Dll'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\Syncopq\bin\Debug\'
    TargetFolder: '$(build.artifactstagingdirectory)\Dll'
    CleanTargetFolder: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\Packages'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\.packages\.nupkg'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\Packages'
    CleanTargetFolder: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;'
    publishVstsFeed: '0b85ebc7-d3b9-4844-886e-848213247f91'
    allowPackageConflicts: true
